apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: movies.com
      http:
        paths:
          - path: /movies/create
            pathType: Prefix
            backend:
              service:
                name: movies-clusterip-srv
                port:
                  number: 4002
          - path: /movies
            pathType: Prefix
            backend:
              service:
                name: query-srv
                port:
                  number: 4007
          - path: /movies/?(.*)/comments
            pathType: Prefix
            backend:
              service:
                name: reviews-srv
                port:
                  number: 4001
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
